language: R
cache: packages
warnings_are_errors: true
r_packages:
  - covr
  
r_github_packages:
  - r-lib/covr  

after_success:
    - Rscript -e 'covr::codecov()'
    
env:
  global:
  - NOT_CRAN="true"
