language: R
cache: packages
warnings_are_errors: true
r_packages:
  - covr
  
after_success:
    - Rscript -e 'covr::codecov()'
    
env:
  global:
  - NOT_CRAN="true"
  - secure: "hjt91w7kESITFX+cjklGw7rwAH94HH6mqDoyN1Aj+5VQOtuwdzXfeldvtHu1eZNs50fU62dPfIOOjxw/opAE5U6VUvlsjBxAj1iyzOaOx5l8ZNarZAabXLj4HtB1flZFPy+kD2bSPnzEqrcAL+8uO11XJBNjRLsKkebXQ+9UoGFptO4z9do1/OgxsssTuD1TehSS0zUPTfoWzd2qzofP5mxuaCXf+56o6gGllyR2bcQtL+Jg8XrNz6m8u/0tY8MQD+2ienj+EE941ali/xBbOGJLN3/bH/InbXMOjODk6Ij6xus0q02vIGo5IclWeQ4ROsg43stPfRr7Rv0avTJr46OAOUXrhuWIMV0T3HaVQH7NJK64hE4U0coNRu/CXwuVkNe4gol28u8/ExLGu/C8Dd7GQ0mD3am/s1bleISyaaw4kIt+vWv3ACzVM8fs805Ecj1s9G34ODMLyqprGQOh35WFdwK6KhhdnGx7eLgch1C2LbzGAxbjUOzixkqedyHyCkJrN6Kb8BAAJo3+sF2Evy+mVNseVC/gyYbNSWxwONoODIcI7PreUg1vwODhyIIHjACeddrSOuroDvwZ9lsqSyZI/g0f1izUAzI+4tdYW+d10PDnhlyPTSNSJUz/IJkAdT9XagsDce5yMOQbpv7Eh262LJaLY5AsRz8PmlN2DSA="
  - secure: "MiLprAWWCHx9RwqxGA6DDB0xuN6bF+jWmZ+09/+ke4qebrO4edYANWG6FvbZRAirbwj7mvAzLI9HLTDAO124MmSAsh+WkpV+crgrUszfgUs5O/QQpPgiNt0mbsqG6vsSjwOh3yOOg9PJpPfetzWqnY81MCuCTBMqSlhLfJ0md6YCCbeUi4Oy1nHq3/DnzsjWCrVbj7BskjMEZIqENKQKyYdkkMrn5Z1r237WWg+USsCiYKdrl95uOahh+2Iooc2ZHWobJostG0JjpiA8S9eGTgrWoe/JaM3Z+gNjfnvHFgO3ADWL0LduZsKWskjMTIO+FOq8YRne0U7FYFVaZw01bExAoLmIfowbQlYzrwO58V1Pd/2lrFXIiA+iqb5Ub6yfQTgViNN0gwx6pz10fxRHmUhkcQLZBJ9FFxl1d7PPpoDWjXN4+LGgtvZFmjvmR9VoC757ealor9D09IJUnHMAVz3h9+1KnWCvqCDGVq1N0w38uSxxdn6ViRX1vjrp/KIw1vrrHawa00OJ4CytXvhGDXSi4qK4NJXsZ4oajFzDVHcM5oYBSc5rB1N5TS5j/ESE637SIjhoRjk/ViJCRTG/dUSLWaJrEd01WphUyaIHnapEjvgoRXJyCHb8P44Rb9WM73ZIpoc0xpiube+26Kzc4xPOa/+YYjacZjxwsHwy9Jk="

