comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        threshold: 10%

comment: false
language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'

codecov:
  token: 8eb20c48-1460-4205-a0df-989cef60f985